extends:
   - "airbnb-base"
   - "plugin:cypress/recommended"

env:
   browser: true

rules:
   import/no-unresolved: off
   import/extensions: off
   import/no-absolute-path: off
   indent: 
      - "error"
      - 4
