name: Basic Application Run Tests
run-name: "${{ github.workflow }} by @${{ github.actor }}"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build
  start:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build start
