name: ESLint CI
run-name: "${{ github.workflow }} #${{ github.run_number }} by @${{ github.actor }}"

on: [push]

jobs:
  Eslint-Check:
    # Using the latest version of Ubuntu as the operating system for the job.
    runs-on: ubuntu-latest

    # Grants the job permission to read the contents of the repository and to write security events.
    # This is necessary for the job to be able to run ESLint and upload the analysis results to GitHub.
    permissions:
      contents: read
      security-events: write

    steps:
      # Checks out the code from the repository so that it can be used in subsequent steps.
      - uses: actions/checkout@v3

      # Set up a Node.js environment with version 18.
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Install AirBnB ESLint config
        run: |
          npm install eslint-config-airbnb-base
          npx install-peerdeps eslint-config-airbnb-base

      - name: Run ESLint
        run: npx eslint src/lib src/scripts
          --config .eslintrc.yml
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true