name: Hadolint
run-name: "${{ github.workflow }} #${{ github.run_number }} by @${{ github.actor }}"

on: [push]

# Necessary to fetch the code that needs to be analyzed by Hadolint.
permissions:
  contents: read

jobs:
  Hadolint-Check:
    # Using the latest version of Ubuntu as the operating system for the job.
    runs-on: ubuntu-latest

    # The permissions required for the Hadolint-Check job to run successfully.
    permissions:
      # The job needs read access to the contents of the repository in order to fetch the code that needs to be analyzed by Hadolint.
      contents: read

      # It also needs write access to security events in order to upload the SARIF results to GitHub.
      security-events: write

      # Finally, it needs read access to actions, but only if the repository is private, in order to get the Action run status.
      actions: read

    steps:
      # Checks out the code from the repository so that it can be used in subsequent steps.
      - uses: actions/checkout@v3

      # Running the Hadolint tool on a Dockerfile located in the repository.
      - name: Run Hadolint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      # Uploading the results of the ESLint analysis to GitHub using the CodeQL Action.
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
